# Generated by Django 5.2.5 on 2025-08-11 21:50

import requests
from django.db import migrations
from recommendations.fixtures import divisions
from decouple import config


def seed_data(apps, schema_editor):
    Division = apps.get_model("recommendations", "Division")
    District = apps.get_model("recommendations", "District")

    # seed the division model
    division_objects = [
        Division(id=div["id"], name=div["name"], bn_name=div["bn_name"])
        for div in divisions
    ]
    Division.objects.bulk_create(division_objects)

    # Fetch and seed the District model
    try:
        url = config("DISTRICTS_JSON_URL")
        response = requests.get(url)
        response.raise_for_status()
        districts_data = response.json()["districts"]

        district_objects = []
        for district in districts_data:
            district_objects.append(
                District(
                    division_id=district["division_id"],
                    name=district["name"],
                    bn_name=district["bn_name"],
                    latitude=float(district["lat"]),
                    longitude=float(district["long"]),
                )
            )
        District.objects.bulk_create(district_objects)

    except requests.exceptions.RequestException as e:
        print(f"Failed to fetch district data: {e}")
    except KeyError as e:
        print(f"Missing key in JSON data: {e}")


def reverse_seed_data(apps, schema_editor):
    # This function is used to reverse the migration
    Division = apps.get_model("recommendations", "Division")
    District = apps.get_model("recommendations", "District")

    Division.objects.all().delete()
    District.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data),
    ]
