# Generated by Django 5.2.5 on 2025-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='avg_pm2_5',
            field=models.FloatField(blank=True, help_text='Avg PM2.5 over 7 days', null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='avg_temp_2pm',
            field=models.FloatField(blank=True, help_text='Avg temp at 2 PM over 7 days', null=True),
        ),
    ]
